language: node_js
node_js:
  - "5.5.0"
install: npm install
script: gulp build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: dist
  target_branch: gh-pages
  on:
    branch: master
